#
# usage: hydra/launcher=slurm_goedel
#
defaults:
  - submitit_slurm

partition: turing
cpus_per_task: 3  # on goedel, we have 3 CPUs per GPU
mem_gb: 10
timeout_min: 99999  # 99999 minutes = a few months

additional_parameters:
  gres: "gpu:1"